
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GlobalState from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Maket Official",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
      <Navbar />
      <div className="bg-base-100">
        {children}
      </div>
        <Footer />
        </GlobalState>
        </body>
    </html>
  );
}
